# Generated by Django 6.1.1 on 2026-09-03 10:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bmoni_user_id", models.CharField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "smart_wallet_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "wallet_address",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("onboarding_complete", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "currency",
                    models.CharField(
                        choices=[("USD", "US Dollar"), ("NGN", "Nigerian Naira")],
                        max_length=3,
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("credit", "Credit"), ("debit", "Debit")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("freelance_income", "Freelance Income"),
                            ("business_income", "Business Income"),
                            ("employment", "Employment"),
                            ("family_support", "Family Support"),
                            ("entertainment", "Entertainment"),
                            ("business_expense", "Business Expense"),
                            ("business_tool", "Business Tool"),
                            ("transport", "Transport"),
                            ("food", "Food & Groceries"),
                            ("utilities", "Utilities"),
                            ("transfer_out", "Transfer Out"),
                            ("transfer_in", "Transfer In"),
                            ("conversion", "Currency Conversion"),
                            ("other_income", "Other Income"),
                            ("other_expense", "Other Expense"),
                        ],
                        max_length=30,
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("reference", models.CharField(blank=True, default="", max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="api.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="FinancialSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("health_score", models.IntegerField(default=50)),
                (
                    "total_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_ngn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "monthly_income_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "monthly_spending_usd",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "monthly_income_ngn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "monthly_spending_ngn",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="api.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "User"), ("assistant", "NURU AI")],
                        max_length=10,
                    ),
                ),
                ("content", models.TextField()),
                (
                    "action_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("action_data", models.JSONField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to="api.userprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp"],
            },
        ),
    ]
