# Generated by Django 6.1.1 on 2026-09-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="face_enrolled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="face_image_data",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="transaction_pin_hash",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
