# Generated by Django 6.1.1 on 2026-09-09 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_userprofile_user_otp_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_text', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='goals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=200)),
                ('business_size', models.CharField(blank=True, choices=[('solo', 'Just me'), ('small', 'Small (2-10 people)'), ('medium', 'Medium (11+ people)')], default='', max_length=10)),
                ('has_employees', models.BooleanField(blank=True, null=True)),
                ('avg_employee_pay', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('spend_categories', models.JSONField(blank=True, default=list)),
                ('avg_monthly_revenue_range', models.CharField(blank=True, choices=[('under_100k', 'Under ₦100,000'), ('100k_500k', '₦100,000 - ₦500,000'), ('500k_2m', '₦500,000 - ₦2,000,000'), ('2m_10m', '₦2,000,000 - ₦10,000,000'), ('over_10m', 'Over ₦10,000,000')], default='', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('onboarding_step_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('date_taken', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('lender_name', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_taken'],
            },
        ),
    ]
