# Generated by Django 6.1.1 on 2026-09-09 07:41

import api.crypto
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_businessprofile_businessgoal_loan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mono', 'Mono')], default='mono', max_length=20)),
                ('mono_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('institution_name', models.CharField(blank=True, default='', max_length=200)),
                ('account_name', models.CharField(blank=True, default='', max_length=200)),
                ('account_number_masked', models.CharField(blank=True, default='', max_length=32)),
                ('mono_access_token', api.crypto.EncryptedTextField(blank=True, default='')),
                ('mono_ref', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Link started'), ('connected', 'Connected'), ('failed', 'Link failed'), ('disconnected', 'Disconnected')], default='pending', max_length=20)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('mono_account_id__gt', '')), fields=('user', 'mono_account_id'), name='uniq_user_mono_account')],
            },
        ),
    ]
