# Generated by Django 6.1.1 on 2026-09-09 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_connectedaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='smart_wallet_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='wallet_address',
        ),
    ]
