# Generated by Django 6.1.1 on 2026-09-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_bmoni_wallet_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="onboarding_complete",
        ),
    ]
