# Generated by Django 6.1.1 on 2026-09-11 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_remove_onboarding_complete"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionSecurity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pin_hash", models.CharField(blank=True, default="", max_length=128)),
                ("pin_set_at", models.DateTimeField(blank=True, null=True)),
                ("pin_failed_attempts", models.PositiveSmallIntegerField(default=0)),
                ("pin_locked_until", models.DateTimeField(blank=True, null=True)),
                ("last_face_check_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_security",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
