# Generated by Django 6.1.1 on 2026-09-10 07:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_userprofile_face_enrolled_and_more"),
        ("api", "0006_remove_onboarding_complete"),
    ]

    operations = []
