# Generated by Django 6.1.1 on 2026-09-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_merge_20260910_0855"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="smart_account_address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
